[project]
authors = ["mikedecr <mgdecrescenzo@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "delayplyr"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
r-base = ">=4.5.1,<4.6"
r-palmerpenguins = ">=0.1.1,<0.2"
r-dplyr = ">=1.1.4,<2"
r-purrr = ">=1.1.0,<2"
r-rlang = ">=1.1.6,<2"
quarto = ">=1.8.24,<2"
r-rmarkdown = ">=2.29,<3"
r-knitr = ">=1.50,<2"
